name: authenticationapp
description: A new Flutter project.

# Prevents accidental publishing to pub.dev
publish_to: 'none' 

# Versioning for the app
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  google_sign_in: ^6.2.2
  cloud_firestore: 5.6.1
  the_apple_sign_in: ^1.1.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/google.png.png
    - assets/apple.png.png
    - assets/firebase.png.png
